"""Structured log pattern diagnostics for gcdoctor.

Provides rule-based, single-line diagnosis of GEOS-Chem log messages.
Each rule returns one or more ``{"level", "item", "message"}`` dicts with
likely causes and recommended checks.
"""


def diagnose_log_line(line: str) -> list[dict]:
    """Return structured diagnosis entries for a single log line.

    Parameters
    ----------
    line:
        One line of GEOS-Chem log text.

    Returns
    -------
    list[dict]
        Zero or more diagnosis entries.
    """
    results: list[dict] = []
    lower_line = line.lower()

    # Rule 1: BoundaryConditions field missing
    _bc_missing = "cannot find field" in lower_line and "bc_" in lower_line
    if _bc_missing:
        results.append(
            {
                "level": "ERROR",
                "item": "log diagnosis",
                "message": "Likely issue: BoundaryConditions species are missing or incompatible with the current GEOS-Chem mechanism.",
            }
        )
        results.append(
            {
                "level": "WARN",
                "item": "log diagnosis",
                "message": "Recommended check: confirm that BoundaryConditions files were generated by the same GEOS-Chem version and chemical mechanism as the nested run.",
            }
        )

    # Rule 2: generic HEMCO field missing (no BC_ prefix)
    _generic_missing = "cannot find field" in lower_line and "bc_" not in lower_line
    if _generic_missing:
        results.append(
            {
                "level": "ERROR",
                "item": "log diagnosis",
                "message": "Likely issue: HEMCO could not find a required input field.",
            }
        )
        results.append(
            {
                "level": "WARN",
                "item": "log diagnosis",
                "message": "Recommended check: inspect HEMCO_Config.rc field names, file paths, and input NetCDF variable names.",
            }
        )

    # Rule 3: input data file missing
    _file_missing_markers = [
        "no such file or directory",
        "file not found",
        "cannot open file",
        "could not open file",
    ]
    if any(marker in lower_line for marker in _file_missing_markers):
        results.append(
            {
                "level": "ERROR",
                "item": "log diagnosis",
                "message": "Likely issue: a required input data file is missing or the configured path is wrong.",
            }
        )
        results.append(
            {
                "level": "WARN",
                "item": "log diagnosis",
                "message": "Recommended check: run a GEOS-Chem dry-run and verify HEMCO_Config.rc path expansion.",
            }
        )

    # Rule 4: NetCDF file corruption or format problem
    _netcdf_markers = [
        "netcdf: unknown file format",
        "unknown file format",
        "netcdf error",
    ]
    if any(marker in lower_line for marker in _netcdf_markers):
        results.append(
            {
                "level": "ERROR",
                "item": "log diagnosis",
                "message": "Likely issue: a NetCDF input file may be corrupted, incomplete, or not readable.",
            }
        )
        results.append(
            {
                "level": "WARN",
                "item": "log diagnosis",
                "message": "Recommended check: inspect the file with ncdump -h and re-download it if needed.",
            }
        )

    # Rule 5: MAPL / regridding / grid problem
    _grid_markers = [
        "mapl error",
        "regrid",
        "flexgrid",
        "grid mismatch",
    ]
    if any(marker in lower_line for marker in _grid_markers):
        results.append(
            {
                "level": "ERROR",
                "item": "log diagnosis",
                "message": "Likely issue: grid, regridding, or MAPL-related processing failed.",
            }
        )
        results.append(
            {
                "level": "WARN",
                "item": "log diagnosis",
                "message": "Recommended check: verify grid resolution, nested-domain bounds, meteorology files, and regridding inputs.",
            }
        )

    # Rule 6: memory or crash issue
    _crash_markers = [
        "segmentation fault",
        "floating point exception",
        "out of memory",
        "killed",
    ]
    if any(marker in lower_line for marker in _crash_markers):
        results.append(
            {
                "level": "ERROR",
                "item": "log diagnosis",
                "message": "Likely issue: the model crashed because of memory, numerical instability, or a low-level runtime error.",
            }
        )
        results.append(
            {
                "level": "WARN",
                "item": "log diagnosis",
                "message": "Recommended check: inspect the last model timestep, memory usage, OpenMP settings, and recent input files.",
            }
        )

    return results
